// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2024/8/20 上午9:16:38
const configMerger = require("/Users/uniza/WorkSpace/homeStayDash/frontend/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: ["/Users/uniza/WorkSpace/homeStayDash/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/uniza/WorkSpace/homeStayDash/frontend/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/uniza/WorkSpace/homeStayDash/frontend/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/uniza/WorkSpace/homeStayDash/frontend/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/uniza/WorkSpace/homeStayDash/frontend/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/uniza/WorkSpace/homeStayDash/frontend/plugins/**/*.{js,ts,mjs}","/Users/uniza/WorkSpace/homeStayDash/frontend/composables/**/*.{js,ts,mjs}","/Users/uniza/WorkSpace/homeStayDash/frontend/utils/**/*.{js,ts,mjs}","/Users/uniza/WorkSpace/homeStayDash/frontend/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/uniza/WorkSpace/homeStayDash/frontend/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/uniza/WorkSpace/homeStayDash/frontend/app.config.{js,ts,mjs}"] }));

module.exports = config
